/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js projects and checked in here so TypeScript
// understands the app before dependencies are installed.
